### PR TITLE
Slack config view

### LINKED ISSUE #97: Allow dynamic GUI config of Slack integration
We should add a view for managing Slack config to the Admin settings page. Should include button/route for sending test message. Should retain backwards compatibility for initializing values from env vars

### LINKED ISSUE #102: Add persistence for configuration settings
We can edit slack configuration variables after #97, but the current method of changing these variables does not persist over different server sessions.

For this configuration data, when would be the appropriate time to read this data? The current structure of the application factory doesn't have a clean insert point (configuration data is read from the environment before the database is activated).

### PR DESCRIPTION
**Pull request by wisygig**
This PR:

* Resolves #97.
* Resolves #102.
* Adds bower management to README.rst

### CODE REVIEW

**Comment by wisygig** [comment]
Interesting enough, my `flask test` fails locally, due to `league/app/league/static/` only containing a `.gitkeep` file.

**Comment by hndrewaall** [comment]
you gotta build your assets first

**Comment by wisygig** [comment]
looks like a problem with the quickstart faq then.

**Comment by wisygig** [comment]
I wish alembic was truly magical.

**Comment by hndrewaall** [comment]
sweet, thanks dude!

**Pull request merged**
